before_script: 
  - mysql -e 'CREATE DATABASE dft_test;'
  - cp config/database.yml.travis config/database.yml

language: ruby

rvm: 
  - 2.5.1

script: 
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec 

services: 
  - mysql