before_script: 
  - mysql -e 'CREATE DATABASE dft_test;'
  - cp config/database.yml.travis config/database.yml
  
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('dft') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pdft
  - sudo service mysql restart

language: ruby

rvm: 
  - 2.5.1

script: 
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec 

services: 
  - mysql